# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download
      working-directory: Task_8-Testing_Task_Management_REST_API

    - name: Tidy-up modules
      run: go mod tidy
      working-directory: Task_8-Testing_Task_Management_REST_API
      
    - name: Usecase Test
      run: go test ./usecases -v -coverprofile=coverage_usecases.out -covermode=atomic
      working-directory: Task_8-Testing_Task_Management_REST_API  

    - name: Controller Test
      run: go test ./delivery/controller -v -coverprofile=coverage_controller.out -covermode=atomic
      working-directory: Task_8-Testing_Task_Management_REST_API

    - name: Middelware Test
      run: go test ./infrastructure -v -coverprofile=coverage_middelware.out -covermode=atomic
      working-directory: Task_8-Testing_Task_Management_REST_API
      
